// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#include <linux/loop.h>

#ifndef __NR_memfd_create
#define __NR_memfd_create 319
#endif

static unsigned long long procid;

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

//% This code is derived from puff.{c,h}, found in the zlib development. The
//% original files come with the following copyright notice:

//% Copyright (C) 2002-2013 Mark Adler, all rights reserved
//% version 2.3, 21 Jan 2013
//% This software is provided 'as-is', without any express or implied
//% warranty.  In no event will the author be held liable for any damages
//% arising from the use of this software.
//% Permission is granted to anyone to use this software for any purpose,
//% including commercial applications, and to alter it and redistribute it
//% freely, subject to the following restrictions:
//% 1. The origin of this software must not be misrepresented; you must not
//%    claim that you wrote the original software. If you use this software
//%    in a product, an acknowledgment in the product documentation would be
//%    appreciated but is not required.
//% 2. Altered source versions must be plainly marked as such, and must not be
//%    misrepresented as being the original software.
//% 3. This notice may not be removed or altered from any source distribution.
//% Mark Adler    madler@alumni.caltech.edu

//% BEGIN CODE DERIVED FROM puff.{c,h}

#define MAXBITS 15
#define MAXLCODES 286
#define MAXDCODES 30
#define MAXCODES (MAXLCODES + MAXDCODES)
#define FIXLCODES 288

struct puff_state {
  unsigned char* out;
  unsigned long outlen;
  unsigned long outcnt;
  const unsigned char* in;
  unsigned long inlen;
  unsigned long incnt;
  int bitbuf;
  int bitcnt;
  jmp_buf env;
};
static int puff_bits(struct puff_state* s, int need)
{
  long val = s->bitbuf;
  while (s->bitcnt < need) {
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    val |= (long)(s->in[s->incnt++]) << s->bitcnt;
    s->bitcnt += 8;
  }
  s->bitbuf = (int)(val >> need);
  s->bitcnt -= need;
  return (int)(val & ((1L << need) - 1));
}
static int puff_stored(struct puff_state* s)
{
  s->bitbuf = 0;
  s->bitcnt = 0;
  if (s->incnt + 4 > s->inlen)
    return 2;
  unsigned len = s->in[s->incnt++];
  len |= s->in[s->incnt++] << 8;
  if (s->in[s->incnt++] != (~len & 0xff) ||
      s->in[s->incnt++] != ((~len >> 8) & 0xff))
    return -2;
  if (s->incnt + len > s->inlen)
    return 2;
  if (s->outcnt + len > s->outlen)
    return 1;
  for (; len--; s->outcnt++, s->incnt++) {
    if (s->in[s->incnt])
      s->out[s->outcnt] = s->in[s->incnt];
  }
  return 0;
}
struct puff_huffman {
  short* count;
  short* symbol;
};
static int puff_decode(struct puff_state* s, const struct puff_huffman* h)
{
  int first = 0;
  int index = 0;
  int bitbuf = s->bitbuf;
  int left = s->bitcnt;
  int code = first = index = 0;
  int len = 1;
  short* next = h->count + 1;
  while (1) {
    while (left--) {
      code |= bitbuf & 1;
      bitbuf >>= 1;
      int count = *next++;
      if (code - count < first) {
        s->bitbuf = bitbuf;
        s->bitcnt = (s->bitcnt - len) & 7;
        return h->symbol[index + (code - first)];
      }
      index += count;
      first += count;
      first <<= 1;
      code <<= 1;
      len++;
    }
    left = (MAXBITS + 1) - len;
    if (left == 0)
      break;
    if (s->incnt == s->inlen)
      longjmp(s->env, 1);
    bitbuf = s->in[s->incnt++];
    if (left > 8)
      left = 8;
  }
  return -10;
}
static int puff_construct(struct puff_huffman* h, const short* length, int n)
{
  int len;
  for (len = 0; len <= MAXBITS; len++)
    h->count[len] = 0;
  int symbol;
  for (symbol = 0; symbol < n; symbol++)
    (h->count[length[symbol]])++;
  if (h->count[0] == n)
    return 0;
  int left = 1;
  for (len = 1; len <= MAXBITS; len++) {
    left <<= 1;
    left -= h->count[len];
    if (left < 0)
      return left;
  }
  short offs[MAXBITS + 1];
  offs[1] = 0;
  for (len = 1; len < MAXBITS; len++)
    offs[len + 1] = offs[len] + h->count[len];
  for (symbol = 0; symbol < n; symbol++)
    if (length[symbol] != 0)
      h->symbol[offs[length[symbol]]++] = symbol;
  return left;
}
static int puff_codes(struct puff_state* s, const struct puff_huffman* lencode,
                      const struct puff_huffman* distcode)
{
  static const short lens[29] = {3,  4,  5,  6,   7,   8,   9,   10,  11, 13,
                                 15, 17, 19, 23,  27,  31,  35,  43,  51, 59,
                                 67, 83, 99, 115, 131, 163, 195, 227, 258};
  static const short lext[29] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2,
                                 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0};
  static const short dists[30] = {
      1,    2,    3,    4,    5,    7,    9,    13,    17,    25,
      33,   49,   65,   97,   129,  193,  257,  385,   513,   769,
      1025, 1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577};
  static const short dext[30] = {0, 0, 0,  0,  1,  1,  2,  2,  3,  3,
                                 4, 4, 5,  5,  6,  6,  7,  7,  8,  8,
                                 9, 9, 10, 10, 11, 11, 12, 12, 13, 13};
  int symbol;
  do {
    symbol = puff_decode(s, lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 256) {
      if (s->outcnt == s->outlen)
        return 1;
      if (symbol)
        s->out[s->outcnt] = symbol;
      s->outcnt++;
    } else if (symbol > 256) {
      symbol -= 257;
      if (symbol >= 29)
        return -10;
      int len = lens[symbol] + puff_bits(s, lext[symbol]);
      symbol = puff_decode(s, distcode);
      if (symbol < 0)
        return symbol;
      unsigned dist = dists[symbol] + puff_bits(s, dext[symbol]);
      if (dist > s->outcnt)
        return -11;
      if (s->outcnt + len > s->outlen)
        return 1;
      while (len--) {
        if (dist <= s->outcnt && s->out[s->outcnt - dist])
          s->out[s->outcnt] = s->out[s->outcnt - dist];
        s->outcnt++;
      }
    }
  } while (symbol != 256);
  return 0;
}
static int puff_fixed(struct puff_state* s)
{
  static int virgin = 1;
  static short lencnt[MAXBITS + 1], lensym[FIXLCODES];
  static short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  static struct puff_huffman lencode, distcode;
  if (virgin) {
    lencode.count = lencnt;
    lencode.symbol = lensym;
    distcode.count = distcnt;
    distcode.symbol = distsym;
    short lengths[FIXLCODES];
    int symbol;
    for (symbol = 0; symbol < 144; symbol++)
      lengths[symbol] = 8;
    for (; symbol < 256; symbol++)
      lengths[symbol] = 9;
    for (; symbol < 280; symbol++)
      lengths[symbol] = 7;
    for (; symbol < FIXLCODES; symbol++)
      lengths[symbol] = 8;
    puff_construct(&lencode, lengths, FIXLCODES);
    for (symbol = 0; symbol < MAXDCODES; symbol++)
      lengths[symbol] = 5;
    puff_construct(&distcode, lengths, MAXDCODES);
    virgin = 0;
  }
  return puff_codes(s, &lencode, &distcode);
}
static int puff_dynamic(struct puff_state* s)
{
  static const short order[19] = {16, 17, 18, 0, 8,  7, 9,  6, 10, 5,
                                  11, 4,  12, 3, 13, 2, 14, 1, 15};
  int nlen = puff_bits(s, 5) + 257;
  int ndist = puff_bits(s, 5) + 1;
  int ncode = puff_bits(s, 4) + 4;
  if (nlen > MAXLCODES || ndist > MAXDCODES)
    return -3;
  short lengths[MAXCODES];
  int index;
  for (index = 0; index < ncode; index++)
    lengths[order[index]] = puff_bits(s, 3);
  for (; index < 19; index++)
    lengths[order[index]] = 0;
  short lencnt[MAXBITS + 1], lensym[MAXLCODES];
  struct puff_huffman lencode = {lencnt, lensym};
  int err = puff_construct(&lencode, lengths, 19);
  if (err != 0)
    return -4;
  index = 0;
  while (index < nlen + ndist) {
    int symbol;
    int len;
    symbol = puff_decode(s, &lencode);
    if (symbol < 0)
      return symbol;
    if (symbol < 16)
      lengths[index++] = symbol;
    else {
      len = 0;
      if (symbol == 16) {
        if (index == 0)
          return -5;
        len = lengths[index - 1];
        symbol = 3 + puff_bits(s, 2);
      } else if (symbol == 17)
        symbol = 3 + puff_bits(s, 3);
      else
        symbol = 11 + puff_bits(s, 7);
      if (index + symbol > nlen + ndist)
        return -6;
      while (symbol--)
        lengths[index++] = len;
    }
  }
  if (lengths[256] == 0)
    return -9;
  err = puff_construct(&lencode, lengths, nlen);
  if (err && (err < 0 || nlen != lencode.count[0] + lencode.count[1]))
    return -7;
  short distcnt[MAXBITS + 1], distsym[MAXDCODES];
  struct puff_huffman distcode = {distcnt, distsym};
  err = puff_construct(&distcode, lengths + nlen, ndist);
  if (err && (err < 0 || ndist != distcode.count[0] + distcode.count[1]))
    return -8;
  return puff_codes(s, &lencode, &distcode);
}
static int puff(unsigned char* dest, unsigned long* destlen,
                const unsigned char* source, unsigned long sourcelen)
{
  struct puff_state s = {
      .out = dest,
      .outlen = *destlen,
      .outcnt = 0,
      .in = source,
      .inlen = sourcelen,
      .incnt = 0,
      .bitbuf = 0,
      .bitcnt = 0,
  };
  int err;
  if (setjmp(s.env) != 0)
    err = 2;
  else {
    int last;
    do {
      last = puff_bits(&s, 1);
      int type = puff_bits(&s, 2);
      err = type == 0 ? puff_stored(&s)
                      : (type == 1 ? puff_fixed(&s)
                                   : (type == 2 ? puff_dynamic(&s) : -1));
      if (err != 0)
        break;
    } while (!last);
  }
  *destlen = s.outcnt;
  return err;
}

//% END CODE DERIVED FROM puff.{c,h}

#define ZLIB_HEADER_WIDTH 2

static int puff_zlib_to_file(const unsigned char* source,
                             unsigned long sourcelen, int dest_fd)
{
  if (sourcelen < ZLIB_HEADER_WIDTH)
    return 0;
  source += ZLIB_HEADER_WIDTH;
  sourcelen -= ZLIB_HEADER_WIDTH;
  const unsigned long max_destlen = 132 << 20;
  void* ret = mmap(0, max_destlen, PROT_WRITE | PROT_READ,
                   MAP_PRIVATE | MAP_ANON, -1, 0);
  if (ret == MAP_FAILED)
    return -1;
  unsigned char* dest = (unsigned char*)ret;
  unsigned long destlen = max_destlen;
  int err = puff(dest, &destlen, source, sourcelen);
  if (err) {
    munmap(dest, max_destlen);
    errno = -err;
    return -1;
  }
  if (write(dest_fd, dest, destlen) != (ssize_t)destlen) {
    munmap(dest, max_destlen);
    return -1;
  }
  return munmap(dest, max_destlen);
}

static int setup_loop_device(unsigned char* data, unsigned long size,
                             const char* loopname, int* loopfd_p)
{
  int err = 0, loopfd = -1;
  int memfd = syscall(__NR_memfd_create, "syzkaller", 0);
  if (memfd == -1) {
    err = errno;
    goto error;
  }
  if (puff_zlib_to_file(data, size, memfd)) {
    err = errno;
    goto error_close_memfd;
  }
  loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    err = errno;
    goto error_close_memfd;
  }
  if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
    if (errno != EBUSY) {
      err = errno;
      goto error_close_loop;
    }
    ioctl(loopfd, LOOP_CLR_FD, 0);
    usleep(1000);
    if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
      err = errno;
      goto error_close_loop;
    }
  }
  close(memfd);
  *loopfd_p = loopfd;
  return 0;

error_close_loop:
  close(loopfd);
error_close_memfd:
  close(memfd);
error:
  errno = err;
  return -1;
}

static void reset_loop_device(const char* loopname)
{
  int loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    return;
  }
  if (ioctl(loopfd, LOOP_CLR_FD, 0)) {
  }
  close(loopfd);
}

static long syz_mount_image(volatile long fsarg, volatile long dir,
                            volatile long flags, volatile long optsarg,
                            volatile long change_dir,
                            volatile unsigned long size, volatile long image)
{
  unsigned char* data = (unsigned char*)image;
  int res = -1, err = 0, need_loop_device = !!size;
  char* mount_opts = (char*)optsarg;
  char* target = (char*)dir;
  char* fs = (char*)fsarg;
  char* source = NULL;
  char loopname[64];
  if (need_loop_device) {
    int loopfd;
    memset(loopname, 0, sizeof(loopname));
    snprintf(loopname, sizeof(loopname), "/dev/loop%llu", procid);
    if (setup_loop_device(data, size, loopname, &loopfd) == -1)
      return -1;
    close(loopfd);
    source = loopname;
  }
  mkdir(target, 0777);
  char opts[256];
  memset(opts, 0, sizeof(opts));
  if (strlen(mount_opts) > (sizeof(opts) - 32)) {
  }
  strncpy(opts, mount_opts, sizeof(opts) - 32);
  if (strcmp(fs, "iso9660") == 0) {
    flags |= MS_RDONLY;
  } else if (strncmp(fs, "ext", 3) == 0) {
    bool has_remount_ro = false;
    char* remount_ro_start = strstr(opts, "errors=remount-ro");
    if (remount_ro_start != NULL) {
      char after = *(remount_ro_start + strlen("errors=remount-ro"));
      char before = remount_ro_start == opts ? '\0' : *(remount_ro_start - 1);
      has_remount_ro = ((before == '\0' || before == ',') &&
                        (after == '\0' || after == ','));
    }
    if (strstr(opts, "errors=panic") || !has_remount_ro)
      strcat(opts, ",errors=continue");
  } else if (strcmp(fs, "xfs") == 0) {
    strcat(opts, ",nouuid");
  } else if (strncmp(fs, "gfs2", 4) == 0 &&
             (strstr(opts, "errors=panic") || strstr(opts, "debug"))) {
    strcat(opts, ",errors=withdraw");
  }
  res = mount(source, target, fs, flags, opts);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  res = open(target, O_RDONLY | O_DIRECTORY);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  if (change_dir) {
    res = chdir(target);
    if (res == -1) {
      err = errno;
    }
  }

error_clear_loop:
  if (need_loop_device)
    reset_loop_device(loopname);
  errno = err;
  return res;
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void reset_loop()
{
  char buf[64];
  snprintf(buf, sizeof(buf), "/dev/loop%llu", procid);
  int loopfd = open(buf, O_RDWR);
  if (loopfd != -1) {
    ioctl(loopfd, LOOP_CLR_FD, 0);
    close(loopfd);
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    reset_loop();
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      sleep_ms(10);
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

void execute_one(void)
{
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  //  syz_mount_image$hfsplus arguments: [
  //    fs: ptr[in, buffer] {
  //      buffer: {68 66 73 70 6c 75 73 00} (length 0x8)
  //    }
  //    dir: ptr[in, buffer] {
  //      buffer: {2e 2f 66 69 6c 65 30 00} (length 0x8)
  //    }
  //    flags: mount_flags = 0x0 (8 bytes)
  //    opts: ptr[in, fs_options[hfsplus_options]] {
  //      fs_options[hfsplus_options] {
  //        elems: array[fs_opt_elem[hfsplus_options]] {
  //          fs_opt_elem[hfsplus_options] {
  //            elem: union hfsplus_options {
  //              nls: fs_opt["nls", stringnoz[codepages_names]] {
  //                name: buffer: {6e 6c 73} (length 0x3)
  //                eq: const = 0x3d (1 bytes)
  //                val: buffer: {63 70 38 36 39} (length 0x5)
  //              }
  //            }
  //            comma: const = 0x2c (1 bytes)
  //          }
  //          fs_opt_elem[hfsplus_options] {
  //            elem: union hfsplus_options {
  //              umask: fs_opt["umask", fmt[oct, int32]] {
  //                name: buffer: {75 6d 61 73 6b} (length 0x5)
  //                eq: const = 0x3d (1 bytes)
  //                val: int32 = 0x8 (23 bytes)
  //              }
  //            }
  //            comma: const = 0x2c (1 bytes)
  //          }
  //          fs_opt_elem[hfsplus_options] {
  //            elem: union hfsplus_options {
  //              barrier: buffer: {62 61 72 72 69 65 72} (length 0x7)
  //            }
  //            comma: const = 0x2c (1 bytes)
  //          }
  //          fs_opt_elem[hfsplus_options] {
  //            elem: union hfsplus_options {
  //              uid: fs_opt["uid", fmt[hex, uid]] {
  //                name: buffer: {75 69 64} (length 0x3)
  //                eq: const = 0x3d (1 bytes)
  //                val: uid (resource)
  //              }
  //            }
  //            comma: const = 0x2c (1 bytes)
  //          }
  //          fs_opt_elem[hfsplus_options] {
  //            elem: union hfsplus_options {
  //              decompose: buffer: {64 65 63 6f 6d 70 6f 73 65} (length 0x9)
  //            }
  //            comma: const = 0x2c (1 bytes)
  //          }
  //          fs_opt_elem[hfsplus_options] {
  //            elem: union hfsplus_options {
  //              type: fs_opt["type", array[int8, 4]] {
  //                name: buffer: {74 79 70 65} (length 0x4)
  //                eq: const = 0x3d (1 bytes)
  //                val: buffer: {fb 5f 1b 4b} (length 0x4)
  //              }
  //            }
  //            comma: const = 0x2c (1 bytes)
  //          }
  //        }
  //        common: array[fs_opt_elem[fs_options_common]] {
  //        }
  //        null: const = 0x0 (1 bytes)
  //      }
  //    }
  //    chdir: int8 = 0xfe (1 bytes)
  //    size: len = 0x5d5 (8 bytes)
  //    img: ptr[in, buffer] {
  //      buffer: (compressed buffer with length 0x5d5)
  //    }
  //  ]
  //  returns fd_dir
  memcpy((void*)0x200000000080, "hfsplus\000", 8);
  memcpy((void*)0x200000000100, "./file0\000", 8);
  memcpy((void*)0x200000000300, "nls", 3);
  *(uint8_t*)0x200000000303 = 0x3d;
  memcpy((void*)0x200000000304, "cp869", 5);
  *(uint8_t*)0x200000000309 = 0x2c;
  memcpy((void*)0x20000000030a, "umask", 5);
  *(uint8_t*)0x20000000030f = 0x3d;
  sprintf((char*)0x200000000310, "%023llo", (long long)8);
  *(uint8_t*)0x200000000327 = 0x2c;
  memcpy((void*)0x200000000328, "barrier", 7);
  *(uint8_t*)0x20000000032f = 0x2c;
  memcpy((void*)0x200000000330, "uid", 3);
  *(uint8_t*)0x200000000333 = 0x3d;
  sprintf((char*)0x200000000334, "0x%016llx", (long long)0);
  *(uint8_t*)0x200000000346 = 0x2c;
  memcpy((void*)0x200000000347, "decompose", 9);
  *(uint8_t*)0x200000000350 = 0x2c;
  memcpy((void*)0x200000000351, "type", 4);
  *(uint8_t*)0x200000000355 = 0x3d;
  memcpy((void*)0x200000000356, "\xfb\x5f\x1b\x4b", 4);
  *(uint8_t*)0x20000000035a = 0x2c;
  *(uint8_t*)0x20000000035b = 0;
  memcpy(
      (void*)0x200000002ac0,
      "\x78\x9c\xec\xdd\x41\x6f\x1c\x67\x19\x07\xf0\xff\x6e\x1c\xc7\x36\x6a\xb2"
      "\x49\x93\x36\xd0\x4a\x58\x45\x02\x84\x45\x62\xef\xa2\x92\xa0\xaa\x40\x29"
      "\xc8\x42\x15\x6a\xc5\x27\xb0\xb0\x53\x5b\x59\xbb\x95\xbd\x45\x6e\x0f\xc8"
      "\x20\xce\xfd\x0c\xe5\x60\xa9\x67\xc4\x15\xa9\x52\x39\xc3\x27\x40\x46\x3d"
      "\x22\x71\x37\x27\xa3\x99\x9d\x5d\x6f\xec\xad\x6b\xd7\xc6\x6b\x37\xbf\x9f"
      "\x34\xfb\x3e\x33\xef\xcc\xbb\xcf\x3c\x3b\x33\x99\x59\x2b\xda\x00\x4f\xad"
      "\xf9\x99\x8c\x6d\xa5\x96\xf9\x99\x37\x36\x8b\xf9\x9d\xed\x56\x7b\x67\xbb"
      "\xb5\xda\x8b\x93\x5c\x4b\x52\x4f\x26\x92\xd4\x8a\xc5\x7f\x49\xf2\x59\xb2"
      "\x95\xee\x94\xaf\xf7\x3a\x06\xda\x43\xde\x7a\xe5\x99\x8f\x3f\x7c\xe1\xd3"
      "\x57\xbb\x73\x13\x7b\x37\xca\xf1\xca\xf5\x6b\x47\x6d\x77\x3c\xfd\x5c\x1a"
      "\xdd\x5c\xcb\xf6\xac\xc6\x6b\x9e\x7a\xbc\xfd\x3d\x9c\x4e\x72\xab\x6a\x61"
      "\xe4\xf6\x7a\xfe\x35\xb4\xfb\x94\xe7\x25\x00\x70\x91\xd5\x92\x2b\xc3\x96"
      "\x37\x92\xa9\x74\x6f\xfe\x8b\xe7\x80\xee\x5d\x71\xf7\x1e\xfb\x52\xdb\x1a"
      "\x75\x02\x00\x00\x00\x70\x0e\x6e\xec\x66\x37\x9b\xb9\x3e\xea\x3c\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\xe0\x32\x39\xf0\xfb\xff\xf5\xee\xa2\xd4\xa6"
      "\x53\xeb\xfd\xfe\xff\x78\xb5\x2c\x55\x7c\xa9\x7d\x32\xea\x04\x00\x00\x00"
      "\x00\x00\x00\x00\xe0\x0c\x7c\x73\x37\xbb\xd9\xcc\xf5\xa4\x9c\x52\xfd\xcd"
      "\xff\xa5\x32\xba\x5d\xbe\x7e\x2d\xef\x65\x23\x4b\x59\xcf\xbd\x6c\x66\x21"
      "\x9d\x74\xb2\x9e\xb9\x24\x8d\x81\x81\xc6\x37\x17\x3a\x9d\xf5\xb9\x63\x6c"
      "\xd9\x1c\xba\x65\xf3\x9c\x76\x18\x00\x00\x00\x00\x00\x00\x00\xbe\x9a\xfe"
      "\x90\xf9\xfe\xdf\xfe\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe0\x42"
      "\xa8\x25\x57\xba\x4d\x39\xdd\xee\xc5\x8d\xd4\xc7\x92\x4c\x24\x19\x2f\xd6"
      "\xdb\x4a\xfe\xd1\x8b\x2f\xb3\x4f\x46\x9d\x00\x00\x00\x00\x9c\x83\x1b\xbb"
      "\xd9\xcd\x66\xae\xf7\xe6\xf7\x6a\xe5\x33\xff\x73\xe5\x73\xff\x44\xde\xcb"
      "\x5a\x3a\x59\x49\x27\xed\x2c\x65\xb1\xfc\x2e\xa0\xfb\xd4\x5f\xdf\xd9\x6e"
      "\xb5\x77\xb6\x5b\xab\xc5\x74\x78\xdc\x9f\xfe\xe7\x44\x69\x94\x23\xa6\xfb"
      "\xdd\xc3\xf0\x77\xbe\x5b\xae\x31\x99\x47\x59\x29\x97\xdc\xcb\x6f\xf2\x4e"
      "\xda\x59\x4c\xbd\xdc\xb2\x70\xb7\x97\xcf\xf0\xbc\x7e\x5f\xe4\x54\xfb\x71"
      "\xe5\x88\x6c\xae\x0c\xc4\x8b\x55\x5b\xec\xf9\x2f\xab\xf6\xdc\x0d\xfd\x9a"
      "\xa5\x51\x56\xe4\x6a\xbf\x22\xb3\x55\x6e\x45\x35\x6e\x1e\x5d\x89\x13\x7e"
      "\x3a\x07\xdf\x69\x2e\xf5\x7e\x4a\xb7\xcf\xa8\xe6\x83\xa6\xaa\xb6\xd8\x9f"
      "\xd7\x47\x55\xf3\xa1\x0e\x56\xa2\x39\x70\xf4\x3d\x77\x74\x25\x92\xa9\x7f"
      "\xb6\xfe\xbb\xdc\x5e\x7b\xbc\xfc\x68\x63\xe6\xe2\xec\xd2\x97\x74\xb0\x12"
      "\xad\x81\x4a\x3c\xff\x54\x55\x62\xb6\xac\xc4\x9d\xfe\xfc\x7c\x7e\x91\x5f"
      "\x67\x26\xd3\x79\x33\xeb\x59\xc9\x6f\xb3\x90\x4e\x96\x32\x9d\xd7\xcb\x68"
      "\xa1\x3a\x9e\x8b\xd7\xc6\xd1\x95\xfa\xc9\x13\x73\x6f\x7e\x51\x26\xe3\xd5"
      "\xe7\xd2\xbd\x7e\x9d\x2c\xa7\x97\xca\x6d\xaf\x67\x25\xbf\xca\x3b\x59\x2c"
      "\xcf\xf2\x07\x69\xa6\x99\x97\xf3\x20\x0f\xd3\x2c\xcf\xfa\xde\x27\x7c\xe7"
      "\x18\x67\x7d\xfd\x64\x67\xfd\xb7\xbe\x5b\x05\x57\x93\xfc\xbc\x6a\x2f\x86"
      "\xa2\xae\x37\x07\xea\x3a\x78\xcd\x6d\x94\x7d\x83\x4b\xf6\xab\x74\xeb\xec"
      "\xaf\x8d\x63\xdf\xa8\x82\xe2\xe8\x79\xed\xc2\x5d\x1b\x6f\x1e\xf8\x57\xa2"
      "\x57\x89\x67\x8f\xae\xc4\x9f\xf6\x8a\xd7\x8d\xf6\xda\xe3\xf5\xe5\x85\x77"
      "\x8f\xf9\x7e\xdf\xa9\xda\xa2\x02\x3f\xbb\x50\x95\x28\x8e\x97\x5b\xc5\x87"
      "\x55\xce\x3d\x79\x74\x14\x7d\xcf\x0e\xed\x9b\x2b\xfb\x6e\xf7\xfb\xea\x87"
      "\xfa\xee\xf4\xfb\xbe\xe8\x4c\x1d\xaf\xee\xe1\x0e\x8f\xd4\x2c\xfb\x9e\x1f"
      "\xda\xd7\x2a\xfb\xee\x0e\xf4\x0d\xbb\xdf\x02\xe0\xc2\x9b\xfa\xde\xd4\xf8"
      "\xe4\xbf\x27\xff\x3e\xf9\xd1\xe4\x1f\x27\x97\x27\xdf\x98\x78\xed\xda\x83"
      "\x6b\x2f\x8e\xe7\xea\xdf\xae\xfe\x68\x6c\xf6\xca\xb7\xeb\x2f\xd6\xfe\x9c"
      "\x8f\xf2\xbb\xfd\xe7\x7f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe0\xcb\xdb\x78\xff\x83\xc7"
      "\x0b\xed\xf6\xd2\xba\x40\x20\x10\xf4\x83\x51\x5f\x99\x80\xff\xb7\xfb\x9d"
      "\xd5\x77\xef\x6f\xbc\xff\xc1\xf7\x57\x56\x17\xde\x5e\x7a\x7b\x69\xed\x07"
      "\xcd\xd6\xcb\x0f\x7f\xd8\x9a\x7b\x38\x77\xff\xd1\x4a\x7b\x69\xb6\xfb\x3a"
      "\xea\x34\x01\x80\x33\xb4\x7f\xd3\x3f\xea\x4c\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x80\xcf\x73\x1e\xff\x9d\x78\xd4\xfb\x08\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x7c\xb5\xcd\xcf\x64"
      "\x6c\x2b\xb5\xcc\xcd\xde\x9b\x2d\xe6\x77\xb6\x5b\xed\x62\xea\xc5\xfb\x6b"
      "\x4e\x24\xa9\x15\xc1\x5f\x93\x7c\x96\x6c\xa5\x3b\xa5\x31\x30\x5c\xed\xf3"
      "\xde\xe7\xad\x57\x9e\xf9\xf8\xc3\x17\x3e\x7d\x75\x7f\xac\x89\xde\xfa\xb5"
      "\xa3\xb6\x3b\x9e\x27\x72\xa9\x1f\xc8\xe9\xb4\xe3\x35\x4f\x3d\xde\xfe\x1e"
      "\x4e\x27\xb9\x55\xb5\x30\x72\xff\x0b\x00\x00\xff\xff\x7b\xc7\x01\xdf",
      1493);
  syz_mount_image(/*fs=*/0x200000000080, /*dir=*/0x200000000100, /*flags=*/0,
                  /*opts=*/0x200000000300, /*chdir=*/0xfe, /*size=*/0x5d5,
                  /*img=*/0x200000002ac0);
  //  truncate arguments: [
  //    file: ptr[in, buffer] {
  //      buffer: {2e 2f 66 69 6c 65 31 00} (length 0x8)
  //    }
  //    len: intptr = 0xeba (8 bytes)
  //  ]
  memcpy((void*)0x200000000240, "./file1\000", 8);
  syscall(__NR_truncate, /*file=*/0x200000000240ul, /*len=*/0xebaul);
}
int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  loop();
  return 0;
}
